steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Pull latest image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/memelord2:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/memelord2', '-t', 'gcr.io/$PROJECT_ID/memelord2:$COMMIT_SHA', '--cache-from', 'gcr.io/$PROJECT_ID/memelord2:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push $COMMIT_SHA'
  waitFor:
    - 'Build'
  args: ['push', 'gcr.io/$PROJECT_ID/memelord2:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push latest'
  waitFor:
    - 'Build'
  args: ['push', 'gcr.io/$PROJECT_ID/memelord2']
 #- name: gcr.io/cloud-builders/gcloud
 #waitFor:
 #- 'Push latest'
 #args: [ compute, instance-groups, managed, rolling-action, restart, memelord-group, --zone=us-central1-a ]
